### ISSUE TITLE
import errors during source install

### ISSUE THREAD

**Issue by MichalPitr** [heruberuto/fever-cs-dataset#3]
Throws errors from `extract_wiki_dump.sh` and `build_db.sh`

```
2020-07-10 09:59:08 (4,70 MB/s) - ‘../data/cswiki-latest-pages-articles.xml.bz2.1’ saved [835617128/835617128]

extract_wiki_dump.sh...
Traceback (most recent call last):
  File "../src/scripts/WikiExtractor.py", line 1, in <module>
    from wikiextractor import WikiExtractor
ImportError: No module named wikiextractor
find: ‘../data/extracted’: No such file or directory
extracted_wiki to jsonl...
  File "../src/scripts/wiki_to_jsonl.py", line 43
SyntaxError: Non-ASCII character '\xe2' in file ../src/scripts/wiki_to_jsonl.py on line 43, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
build db...
Traceback (most recent call last):
  File "../src/scripts/build_db.py", line 12, in <module>
    import importlib.util
ImportError: No module named util
build_tfidf...
Traceback (most recent call last):
  File "../src/scripts/build_tfidf.py", line 11, in <module>
    import pathlib
ImportError: No module named pathlib

```

**Comment by heruberuto** [comment]
Are You using Python or Conda interpreter?
